### PR TITLE
model: MVVM pattern & LiveData

### PR DESCRIPTION
**Pull request by theo-damiani**
Hey everyone!

This is not really a pull request.
I just wanted to push it and create the pull request to explain some details.

I tried to define the MVVM model for the ItemViewActivity:
- for the model: nothing changes. It is the database, which I don't use for now in this branch (I will add it).
- for the view: it is still the ItemView but few things changed: the adapter just 'adapt' the to-do list, so it can be displayed by the ListView Layout. And all the modifications that a user can perform are taken by the view but performs by the view model.
- the view model is defined by the `ItemViewActivityViewModel` (maybe a too long name): it uses mutable live data. When the itemView activity is launched the model view will load the to-do list from the database (for now it is just a new to-do list). And performs any updates that the view sends to the model.

I am not really sure about all this stuff but from what the TA said this morning and my research after our meeting, it seems to be a good start with this new 'architecture'. And so Noah and Leandro get a first draft for their related task #71 and #69.

If you have any suggestions or anything, don't hesitate. 
I never used this stuff, so it is new to me. 

Cheers!

### CODE REVIEW

**Comment by theo-damiani** [comment]
Make changes in the view:
- use a recycler view instead of a list view.
- create the todo adapter in a separate class.
- integrate the volatile database in the model but this leads to lots of problems as the database is not persistent.

The add task button no longer works. I will investigate this error.
But I think the pattern is well defined and you can get an idea to implement in the same way for the list selection view.

Also need to add tests.

**Comment by theo-damiani** [comment]
Hey!

So I think the model is now good.
From the previous push, I fixed the Live Data updating. 
So it solved issue #44: I just need to take a look at the task class (adding a done field).
Also, the item view is fully adapted to the MVVM pattern #72.
Just to explain some details:
- Our current database API doesn't offer the possibility to return LiveData. In many MVVM explanations that I found, they always use a DAO (Data Access Object) and update the database (ROOM) with SQLite queries. So here, I just used the TodoRepository to update the database and take care of exposing only a LiveData instance even if it contains a MutableLiveData.
- This live data is observed in the Item View Activity. The observer takes care to update the TodoAdapter.
- The TodoAdapter just adapts a to-do list so it can be displayed in a recycler view (same as a List view apparently offer more functionality).
- This TodoAdapter notifies also when the data changed so the view is in a way 'rebuild'. The functionality works even if the adapter doesn't notify the view but the view will be less often updated.

I think we can maybe use this pattern for the list selection view, this concerns issues #71, #32.

Other things to note:
- the TodoRepository (maybe not the best name): should take care of getting the instance of the database in the case we have a persistent one. Here we just recreate each time a database.
- I added a public attribute `UUID id` in the Todo Repository to recover which todo list we are displaying in the item view as for now the list selection view doesn't give any info on which todo is selected.

I need to clean the code, remove the print (used to debug), modular some parts (CodeClimate complain of some too long function), and of course implement tests.

Cheers!

**Review by shoutizix — APPROVED** [review]
It's great and I definitely need it to start working on #69 ! I don't see any problem to my point of view but LiveData are also to new to me.

Cheers

**Review by YagoGG — CHANGES_REQUESTED** [review]
Hey @theo-damiani!

Thanks a lot for the PR, it is really clever and the whole implementation is really cool.

It has taken me some time to fully understand the whole MVVM model, but now I feel comfortable with how we use it for the app.

I have left a few minor comments, but otherwise it looks great. Well done! :)

**Review by VPellenc — APPROVED** [review]
I read and reviewed the architectural changes, I didn't find any problem.
Other than what Yago already mentionned the patch looks good to me.

I didn't test the patch on my emulator that said, as I was away from it.

**Review by lgraziano — APPROVED** [review]
Great job ! I read the code and tested it, everything is just fine.

**Review by YagoGG — APPROVED** [review]
Looking great, thanks for the fixes and the amazing work overall @theo-damiani!

**Review by sydneyhauke — APPROVED** [review]
Nice work !

**Pull request merged**
