### PR TITLE
Notes layout

### PR DESCRIPTION
**Pull request by VPellenc**
This PR includes the activities and the Note data class, as well as a placeholder in order to display notes.

### CODE REVIEW

**Comment by theo-damiani** [comment]
As Vincent re-uses this work in PR #83, we can maybe close this one?

**Comment by VPellenc** [comment]
I did this because we decided it in the stand up meeting (separate view and database PRs), but indeed as it stands I still need the view commits in the database PR.
I'm fine with anything personally.

**Comment by theo-damiani** [comment]
Hoo yes sorry, I forgot, do what you prefer

**Review by theo-damiani — APPROVED** [review]

**Review by YagoGG — APPROVED** [review]
Hey @VPellenc! Thanks a lot for the work, it is really exciting to see the notes feature coming to life. :)

I have been able to test it locally and it works like a charm. I would be glad to have this merged in its current state, but it would be great if you could fix the linter warnings (at least the ones not related to hardcoded note content).

Cheers!

**Pull request merged**
