### PR TITLE
fix gradle format conflict

### PR DESCRIPTION
**Pull request by lgraziano**
A little fix for the newline symbol problem on windows.

### CODE REVIEW

**Review by theo-damiani — APPROVED** [review]
Perfect, fix some errors for me! (on windows)
Thanks to @sydneyhauke for the help!

**Comment by theo-damiani** [comment]
Edit: when running spotless with the fix `lineEndings 'UNIX'` on the branch feature/MVVM-ListselectionView it changes all the file (+35)

**Comment by sydneyhauke** [comment]
> Edit: when running spotless with the fix `lineEndings 'UNIX'` on the branch feature/MVVM-ListselectionView it changes all the files (+35)

Are you on Windows as well ? What is the output from spotless check ? Are your local files formatted with CRLF (\r\n) or with LF (\n) line endings ?

**Review by sydneyhauke — APPROVED** [review]
This configuration should force us to have a uniform formatting across all platforms.

**Pull request merged**
