### PR TITLE
Feature/delete task view

### PR DESCRIPTION
**Pull request by shoutizix**
Just added the feature of delete task by longclicking on an item of the list

### CODE REVIEW

**Review by VPellenc — APPROVED** [review]
Reviewed the code and tested on my emulator. Looks good to me.

One thing to keep in mind for the future, we might want to add some sort of confirmation to avoid deleting by mistake.

**Comment by shoutizix** [comment]
That's true I'll open an Issue for that thanks !

**Comment by theo-damiani** [comment]
Hey! 

I just added those commits with mine in the PR #48. Maybe we can close this one and work with the new one I created. 
Is it good for you?

Cheers!

**Comment by shoutizix** [comment]
Yep let's do that

**Pull request closed without merging**
