### PR TITLE
small PR only some design (Drawing activity)

### PR DESCRIPTION
**Pull request by theo-damiani**
Small refactor with the id of the buttons and add some designs.

### CODE REVIEW

**Comment by theo-damiani** [comment]
Thanks for the review @shoutizix !
I made the changes.
But I don't get the error with the erase button, do you have the same problem with the master?

**Comment by shoutizix** [comment]
Nope it works fine on master.. 
It's weird I'll look into that

**Comment by shoutizix** [comment]
I think that maybe the problem comes from my phone anyway this PR looks really great I hope we can merge it really soon !

**Review by sydneyhauke — APPROVED** [review]
Tested and I can confirm everything seems still functional.

Don't forget to address some lint warnings, but otherwise We can merge now.

**Comment by theo-damiani** [comment]
> 
> 
> Tested and I can confirm everything seems still functional.
> 
> Don't forget to address some lint warnings, but otherwise We can merge now.

I took care of this lint warnings!

**Pull request merged**
