### PR TITLE
design: Stylize the current views with the mockups in #55

### LINKED ISSUE #89: Implement the task list view styles from the mockup
Make the view that displays the tasks in a todo list look like the mockup in #55.

### PR DESCRIPTION
**Pull request by YagoGG**
This implements most of the design initially included in our mockups (see #55).

This closes #89, #90 and #91.

### CODE REVIEW

**Comment by YagoGG** [comment]
@theo-damiani tests are fixed! Just an FYI, since you wanted to include this in the demo.

Cheers!

**Review by theo-damiani — APPROVED** [review]
Hey! 
Thanks for this PR, I tested locally and the design looks awesome!
And thank you also for fixing the test!

**Review by lgraziano — APPROVED** [review]
Awesome ! It looks very nice and every function still works, great work 👌

**Comment by YagoGG** [comment]
Solved the merge conflicts and merged to `master`. Thanks, folks!

**Pull request merged**
