### PR TITLE
put drawing in the content of a note

### PR DESCRIPTION
**Pull request by theo-damiani**

### CODE REVIEW

**Comment by theo-damiani** [comment]
> 
> 
> Tested and works well!
> Just need to remove the debugging messages.

yeah, it was just to be sure that it is working. 
I will clean up and I need to store the drawing in the remote database aswell

**Review by shoutizix — APPROVED** [review]
Woaw it works perfectly nice job !!
As Vincent said just remove the debug print and we can merge it !

**Comment by theo-damiani** [comment]
I made little changes, so if you could re-checking that it is working for you, it would be awesome!

**Comment by shoutizix** [comment]
I had a Toast message just after allowing the permission that there was an error but the image actually displayed well. And I just retry to put a drawing after that and it displayed it well but there was also a Toast message that it was Granted. So maybe you can just remove all this Toast messages

**Comment by shoutizix** [comment]
Now it doesn't work anymore with my phone

**Comment by theo-damiani** [comment]
> 
> 
> Now it doesn't work anymore with my phone

AHHHHHHHHHHHH fack

**Comment by theo-damiani** [comment]
Now it should be working!

**Comment by shoutizix** [comment]
Now it works as expected, great job !

**Review by VPellenc — APPROVED** [review]
Works for me as well!

**Pull request merged**
